from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    NOTIFIER_URL: str
    NOTIFIER_CLIENT_ID: str
    NOTIFIER_CLIENT_SECRET: str
    SMS_URL: str
    JWT_SECRET_KEY: str
    JWT_EXPIRY_TIME_MIN: str
    AES_SECRET: str
    GOOGLE_CLIENT_ID: str
    SETU_BASE_URL: str
    SETU_REDIRECT_URL: str
    SETU_CLIENT_ID: str
    SETU_CLIENT_SECRET: str
    SETU_DIGI_LOCKER_PRODUCT_ID: str
    AWS_ACCESS_KEY: str
    AWS_SECRET_ACCESS_KEY: str
    AWS_EXPIRY_DURATION: str
    AWS_ROLE_ARN: str
    AWS_BUCKET_NAME: str
    AWS_STORAGE_PATH: str
    AWS_REGION: str
    IP_GEO_LOCATION: str
    IP_API_KEY: str
    MO_BASE_URL: str
    MO_CLIENT_ID: str
    MO_CLIENT_SECRET: str
    MO_PRODUCT_ID_PAN: str
    MO_PRODUCT_ID_KRA: str
    MO_PRODUCT_ID_DIGILOCKER: str
    MO_PRODUCT_ID_PENNY_DROP: str
    MO_PRODUCT_ID_REVERSE_PENNY_DROP: str
    MO_PRODUCT_ID_ESIGN: str
    MO_DOC_ID_EKYC_AADHAAR_FORM: str
    MO_DOC_ID_EKYC_KRA_FORM: str
    MO_ACCOUNT_AGGREGATOR_PRODUCT_ID: str
    MONGO_CONNECTION_STRING: str
    APPLICATION_SERIES: str
    POPPLER_PATH: str
    EMP_SIGN: str
    EMP_NAME: str
    EMP_DESIGNATION: str
    EMP_ID: str
    DPID: str
    EMAIL_VERIFICATION_TEMPLATE: str
    EMAIL_VERIFICATION_NAME: str
    EMAIL_TRACK_TEMPLATE: str
    EMAIL_TRACK_NAME: str
    MONGODB_MASTER: str
    MONGODB_ONBOARDING: str
    COLLECTION_ONBOARDING_MASTER: str
    MONGO_CLIENT_CONNECTION_STRING: str
    MONGODB_CD_DB: str
    COLLECTION_DEMAT_MASTER: str
    COLLECTION_TARIFF: str
    COLLECTION_ADMIN: str
    COLLECTION_EKYC: str
    COLLECTION_BANK_MASTER: str
    COLLECTION_CLIENT_DETAILS: str
    COLLECTION_SETU_WEBHOOK: str
    COLLECTION_TERMINATED_CLIENTS: str
    SETU_WEBHOOK_RPD_KEY : str
    IP_PROXY_CHECK_BASE_URL: str
    IP_PROXY_CHECK_API_KEY: str
    COMPANY_NAME: str
    DEFAULT_PARTNER_ID: str
    IMAGE_RESOLUTION: int
    FILE_SIZE_LIMIT: float
    PDF_FILE_DPI: int
    MO_DOC_ID_NOMINEE_ANNEXURE_B: str
    MONGODB_CUSTOMER_DOCUMENTS : str
    MONGODB_LOGGERS: str
    COLLECTION_EKYC_LOGGERS: str
    GHOSTSCRIPT_PATH : str
    MAX_PAGE_COUNT: int
    MO_PRODUCT_ID_CAMS_AA: str
    COLLECTION_CAMS_AA_WEBHOOK: str


    class Config:
        env_file = ".env"


settings = Settings()
